dist: bionic
language: php

php:
- 7.4

env:
  global:
  - SETUP=stable
  matrix:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
  - $HOME/.composer/cache

install:
- if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
- if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: false
  slack:
    rooms:
    - secure: ACelL0Ms07xSwnfztATPZKpklmxW1tkSWUcbEuv4WRONEmyk1g95ArP+URDD2Mi1xkG8aIU1jkCCGdHKAFUAiQF99xMPQagMYAQpf+w/0Nm5Xg7UY3J5tJHky9QA+CmrpVx9isZUsazN43NHF2b0Pu8Gy3x0wI8ZuWpdlKOWAaayliw0CntqK4WhTvSC21jluaMA9Cr4OIHhR6RtJgxj5g3mHoblOk3ykIhtzgFsLgON+ptwHPIGUkkougO/CXMJXmEUW/M0fDuVADRk0Pw+WCnB/zK8WG2IyucIpISRVt/KWxkZZfCK5AudwkxdZvf2oIzaLnI6A3qOKYnj9qyWjDNbvSytrfHvm8zHr+V1UVhzIocYZovYcwZydEkxTam8YBsCL9YgUSWG84KXrRu1dcwOZIHqeu81D4znZXQuoYDvFQ7eIjDCvTVBvrdx+sxk0A77QcPZg2DCXlAl/rcoBlFLraH4KJuunktpQy9alDetDznnJjJP2XVq5IGgmu3Tw5YSoO9guWbcha0KtAAZHViHirO5v/Rv7DBp85jzyBd0qV9zA2op+l5sP/VDcQ7y6pRrAjUPmY6zxum75xW6TUDhVBK8LfeKzQxQIDWqUNZ8JmNx1SYpTkNZ2E7/r99X9Zb+ywf2oaPJEq8qqgSvzAFhBTfLpVu0tJqbdV+RWjY=
